gitlab:
  image: gitlab/gitlab-ce:latest
  restart: always
  hostname: ${GITLAB_DOMAIN}
  container_name: gitlab
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://${GITLAB_DOMAIN}'
      registry_external_url 'https://${GITLAB_DOMAIN}:5001'
      nginx['listen_port'] = 80
      nginx['listen_https'] = false
      nginx['proxy_set_headers'] = {
        "X-Forwarded-Proto" => "https",
        "X-Forwarded-Ssl" => "on"
      }
      registry['enable'] = true
      registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/${GITLAB_DOMAIN}.crt"
      registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/${GITLAB_DOMAIN}.key"
      gitlab_rails['gitlab_shell_ssh_port'] = 2222
      gitlab_rails['gitlab_email_enabled'] = true
      gitlab_rails['gitlab_email_from'] = "${GITLAB_EMAIL_FROM}"
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = 'smtp.gmail.com'
      gitlab_rails['smtp_port'] = 587
      gitlab_rails['smtp_user_name'] = "${GITLAB_EMAIL_FROM}"
      gitlab_rails['smtp_password'] = "${GITLAB_SMTP_PASSWORD}"
      gitlab_rails['smtp_domain'] = 'smtp.gmail.com'
      gitlab_rails['smtp_authentication'] = 'login'
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = false
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
  ports:
    - 2222:22
    - 9090:80
    - 5001:5001
  volumes:
    - /srv/gitlab/config:/etc/gitlab
    - /srv/gitlab/logs:/var/log/gitlab
    - /srv/gitlab/data:/var/opt/gitlab
    - /etc/letsencrypt/live/${GITLAB_DOMAIN}/fullchain.pem:/etc/gitlab/ssl/${GITLAB_DOMAIN}.crt
    - /etc/letsencrypt/live/${GITLAB_DOMAIN}/privkey.pem:/etc/gitlab/ssl/${GITLAB_DOMAIN}.key
gitlab-runner:
  image: gitlab/gitlab-runner:latest
  restart: always
  container_name: gitlab-runner
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /srv/gitlab-runner/config:/etc/gitlab-runner
